export { LayoutMain } from './component/LayoutMain'

export { CatalogPage } from '@/pages/main/CatalogPage'
export { HomePage } from '@/pages/main/HomePage'
export { MyFoldersPage } from '@/pages/main/MyFoldersPage'
export { SettingPage } from '@/pages/main/SettingPage'
export { FolderTopicPage } from '@/pages/main/FolderTopicPage'
export { MemorizationPage } from '@/pages/main/MemorizationPage'
export { TestResultPage } from '@/pages/main/TestResultPage'
export { TestPage } from '@/pages/main/TestPage'
