export { LayoutMain } from './component/LayoutMain'

export { CatalogPage } from '@/pages/main/CatalogPage'
export { HomePage } from '@/pages/main/HomePage'
export { MyFoldersPage } from '@/pages/main/MyFoldersPage'
export { SettingPage } from '@/pages/main/SettingPage'
export { FolderTopicPage } from '@/pages/FolderTopicPage'
export { MemorizationPage } from '@/features/testInteractive/ui/interactive/MemorizationPage'
export { TestResultPage } from '@/features/testInteractive/ui/result/TestResultPage'
export { TestPage } from '@/features/testInteractive/ui/interactive/TestPage'
